const lessonTitle = "《论语》四则";

const lessonData = [
    // ===== 第一则 =====
    ["子", "zǐ", "Confucius", "Confucius", "孔子"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["学", "xué", "learn", "belajar", "学习"],
    ["而", "ér", "and", "dan", "而且"],
    ["时", "shí", "at the right time", "pada masa yang sesuai", "按时"],
    ["习", "xí", "practise", "mengulang kaji", "温习"],
    ["之", "zhī", "it", "ia", "它"],
    ["，", "", "", "", ""],
    ["不", "bù", "not", "tidak", "不"],
    ["亦", "yì", "also", "juga", "也"],
    ["说", "yuè", "pleasant", "gembira", "愉快"],
    ["乎", "hū", "?", "kah", "吗"],
    ["？", "", "", "", ""],
    ["有", "yǒu", "have", "ada", "有"],
    ["朋", "péng", "friends", "rakan", "志同道合的朋友"],
    ["自", "zì", "from", "dari", "从"],
    ["远方", "yuǎn fāng", "faraway place", "tempat yang jauh", "远方"],
    ["来", "lái", "come", "datang", "来"],
    ["，", "", "", "", ""],
    ["不", "bù", "not", "tidak", "不"],
    ["亦", "yì", "also", "juga", "也"],
    ["乐", "lè", "happy", "gembira", "快乐"],
    ["乎", "hū", "?", "kah", "吗"],
    ["？", "", "", "", ""],
    ["人", "rén", "people", "orang", "别人"],
    ["不知", "bù zhī", "don't understand", "tidak faham", "不了解"],
    ["而", "ér", "but", "tetapi", "却"],
    ["不", "bù", "not", "tidak", "不"],
    ["愠", "yùn", "get angry", "marah", "生气"],
    ["，", "", "", "", ""],
    ["不", "bù", "not", "tidak", "不"],
    ["亦", "yì", "also", "juga", "也"],
    ["君子", "jūn zǐ", "gentleman", "orang berbudi", "有德行的人"],
    ["乎", "hū", "?", "kah", "吗"],
    ["？”", "", "", "", ""],
    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["学而", "xué ér", "Xue Er", "Xue Er", "学而"],
    ["》", "", "", "", ""],
    ["）", "", "", "", ""],

    ["\n", "", "", ""], // 👈 第一则 → 第二则

    // ===== 第二则 =====
    ["子", "zǐ", "Confucius", "Confucius", "孔子"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["温", "wēn", "review", "mengulang kaji", "温习"],
    ["故", "gù", "old knowledge", "pengetahuan lama", "旧知识"],
    ["而", "ér", "and", "dan", "从而"],
    ["知", "zhī", "know", "tahu", "获得"],
    ["新", "xīn", "new knowledge", "pengetahuan baru", "新知识"],
    ["，", "", "", "", ""],
    ["可以", "kě yǐ", "can", "boleh", "可以"],
    ["为", "wéi", "be", "menjadi", "做"],
    ["师", "shī", "teacher", "guru", "老师"],
    ["矣", "yǐ", "particle", "lah", "了"],
    ["。”", "", "", "", ""],
    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["为政", "wéi zhèng", "Wei Zheng", "Wei Zheng", "为政"],
    ["》", "", "", "", ""],
    ["）", "", "", "", ""],

    ["\n", "", "", ""], // 👈 第二则 → 第三则

    // ===== 第三则 =====
    ["子", "zǐ", "Confucius", "Confucius", "孔子"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["默", "mò", "silently", "secara senyap", "默默地"],
    ["而", "ér", "and", "dan", "地"],
    ["识", "zhì", "remember", "menghafal", "记住"],
    ["之", "zhī", "it", "ia", "它"],
    ["，", "", "", "", ""],
    ["学", "xué", "learn", "belajar", "学习"],
    ["而", "ér", "and", "dan", "而"],
    ["不", "bù", "not", "tidak", "不"],
    ["厌", "yàn", "get bored", "bosan", "满足"],
    ["，", "", "", "", ""],
    ["诲", "huì", "teach", "mengajar", "教导"],
    ["人", "rén", "others", "orang lain", "别人"],
    ["而", "ér", "and", "dan", "而"],
    ["不", "bù", "not", "tidak", "不"],
    ["倦", "juàn", "get tired", "penat", "疲倦"],
    ["，", "", "", "", ""],
    ["何", "hé", "what", "apa", "什么"],
    ["有", "yǒu", "have", "ada", "有"],
    ["于", "yú", "in", "pada", "在"],
    ["我", "wǒ", "me", "saya", "我"],
    ["哉", "zāi", "particle", "!", "呢"],
    ["！”", "", "", "", ""],
    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["述而", "shù ér", "Shu Er", "Shu Er", "述而"],
    ["》", "", "", "", ""],
    ["）", "", "", "", ""],

    ["\n", "", "", ""], // 👈 第三则 → 第四则

    // ===== 第四则 =====
    ["子", "zǐ", "Confucius", "Confucius", "孔子"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["三人", "sān rén", "three people", "tiga orang", "几个人"],
    ["行", "xíng", "walk", "berjalan", "一起走路"],
    ["，", "", "", "", ""],
    ["必", "bì", "must", "mesti", "一定"],
    ["有", "yǒu", "have", "ada", "有"],
    ["我", "wǒ", "my", "saya", "我的"],
    ["师", "shī", "teacher", "guru", "老师"],
    ["焉", "yān", "among them", "di antaranya", "在其中"],
    ["。", "", "", "", ""],
    ["择", "zé", "choose", "memilih", "选择"],
    ["其", "qí", "their", "mereka punya", "他们的"],
    ["善者", "shàn zhě", "good points", "kebaikan", "优点"],
    ["而", "ér", "and", "dan", "就"],
    ["从", "cóng", "follow", "mengikuti", "学习"],
    ["之", "zhī", "them", "ia", "它"],
    ["，", "", "", "", ""],
    ["其", "qí", "their", "mereka punya", "他们的"],
    ["不善者", "bù shàn zhě", "bad points", "keburukan", "缺点"],
    ["而", "ér", "and", "dan", "就"],
    ["改", "gǎi", "correct", "membetulkan", "改正"],
    ["之", "zhī", "them", "ia", "它"],
    ["。”", "", "", "", ""],
    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["述而", "shù ér", "Shu Er", "Shu Er", "述而"],
    ["》", "", "", "", ""],
    ["）", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["论语", "lún yǔ", "The Analects", "Analek", "论语"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
